image:
  file: Dockerfile
- command: >
    flutter doctor &&
    flutter packages get &&
    flutter config --enable-web
vscode:
  extensions:
    - Dart-Code.dart-code@3.2.0-beta.3:Q8QpBkh2t6eRtCWsj7FMzA==
